#!/bin/bash
cd "$(dirname "$(readlink -e "$0")")" || exit 1

webpack="./webpack --progress"
rollup="node_modules/.bin/rollup"

$webpack --config webpack-dev.js
$webpack --config webpack-prod.js
$rollup -c rollup.dev.js
$rollup -c rollup.prod.js

ls -l /tmp/*react*.js
