addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.9.14")
addSbtPlugin("com.earldouglas"    % "xsbt-web-plugin"          % "4.1.0")
addSbtPlugin("com.typesafe.sbt"   % "sbt-git"                  % "1.0.0")
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager"      % "1.6.2")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.32")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"                  % "0.3.7")
addSbtPlugin("se.marcuslonnberg"  % "sbt-docker"               % "1.5.0")
